### ISSUE TITLE
Membuat transaksi

### ISSUE THREAD

**Issue by boyet007** [r3k4/pos#1]
Gan, cara membuat transaksi baru gimana ya??

Thanks..

**Comment by cxssbit** [comment]
Login using Karyawan account

**Comment by fkolondam** [comment]
Gan, saya pas import product kok dpt error begini ya?

![image](https://user-images.githubusercontent.com/20502226/50715759-a3866980-10b9-11e9-854c-e0919385c11d.png)

**Comment by boyet007** [comment]
oke sip
